# Generated by Django 5.2.6 on 2025-10-01 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortinstructor',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_instructors', to='info_site.cohort'),
        ),
        migrations.AlterField(
            model_name='weekcurriculum',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_weeks', to='info_site.course'),
        ),
    ]
